### ISSUE TITLE
TempFile api can only work in go1.11

### ISSUE THREAD

**Issue by davyzhang** [OneOfOne/struct2ts#1]
f, err := ioutil.TempFile("", "s2ts_gen_*.go") //only works in go1.11

Can we have a go1.10 compatible way to do it?

**Comment by OneOfOne** [comment]
@davyzhang my bad, I had go 1.11 at the time and I didn't realize that was a new api.

It's fixed now, and should be compatible with go1.8+, I'll add some tests later when I get a chance so it wouldn't happen again.
