### ISSUE TITLE
Read source from vendor/ folder

### ISSUE THREAD

**Issue by FlipB** [OneOfOne/struct2ts#11]
I have a problem using struct2ts (version 1.0.2) when struct2ts and the package it operates on are not installed in $GOPATH, only vendor/. 
The reason why I do this is because I'm managing my dependencies (including struct2ts) with dep and running go generate in a docker container as part of the build.

Any plans of supporting this way of doing things?

Error message:
```
main.go:112: executing: go run /tmp/s2ts_gen_1549295504494674900_5577006791947779410.go
/tmp/s2ts_gen_1549295504494674900_5577006791947779410.go:10:2: cannot find package "github.com/private_dependency/pkg/dependency_service" in any of:
        /usr/local/go/src/github.com/private_dependency/pkg/dependency_service (from $GOROOT)
        /go/src/github.com/private_dependency/pkg/dependency_service (from $GOPATH)
/tmp/s2ts_gen_1549295504494674900_5577006791947779410.go:11:2: cannot find package "github.com/OneOfOne/struct2ts" in any of:
        /usr/local/go/src/github.com/OneOfOne/struct2ts (from $GOROOT)
        /go/src/github.com/OneOfOne/struct2ts (from $GOPATH)
main.go:119: exit status 1
```

**Comment by OneOfOne** [comment]
I don't personally use `dep`, however a PR is always welcome.

That's weird though, can you try something for me? can you save the generated go file `-s -o gen.go` and run it in the same directory as the rest of your code with `go run`?

**Comment by FlipB** [comment]
The generate code looks correct, i think the issue here is that go does not look for the dependencies in $WorkDir/vendor/, only $GOPATH and  $GOROOT.
I'm not sure how to fix that other than moving the generated file to the repo before executing `go run` on it.

Generated file:
```
// this file was automatically generated using struct2ts -s -o /tmp/out.go dependency_service.StructMessage
package main

import (
        "flag"
        "io"
        "log"
        "os"

        "github.com/private_dependency/pkg/dependency_service"
        "github.com/OneOfOne/struct2ts"
)

func main() {
        log.SetFlags(log.Lshortfile)

        var (
                out = flag.String("o", "-", "output")
                f   = os.Stdout
                err error
        )

        flag.Parse()
        if *out != "-" {
                if f, err = os.OpenFile(*out, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0644); err != nil {
                        panic(err)
                }
                defer f.Close()
        }
        if err = runStruct2TS(f); err != nil {
                panic(err)
        }
}

func runStruct2TS(w io.Writer) error {
        s := struct2ts.New(&struct2ts.Options{
                Indent: "       ",

                NoAssignDefaults: false,
                InterfaceOnly:    false,

                NoConstructor: false,
                MarkOptional:  false,
                NoToObject:    false,
                NoExports:     false,
                NoHelpers:     false,
                NoDate:        false,

                ES6: false,
        })

        s.Add(dependency_service.StructMessage{})

        io.WriteString(w, "// this file was automatically generated, DO NOT EDIT\n")
        return s.RenderTo(w)
}
```

Executing go run:
```
/app # go run /tmp/out.go
/tmp/out.go:10:2: cannot find package "git.teleservice.net/tlw/monitor-service-go/pkg/monitor_service" in any of:
        /usr/local/go/src/git.teleservice.net/tlw/monitor-service-go/pkg/monitor_service (from $GOROOT)
        /go/src/git.teleservice.net/tlw/monitor-service-go/pkg/monitor_service (from $GOPATH)
/tmp/out.go:11:2: cannot find package "github.com/OneOfOne/struct2ts" in any of:
        /usr/local/go/src/github.com/OneOfOne/struct2ts (from $GOROOT)
        /go/src/github.com/OneOfOne/struct2ts (from $GOPATH)

```

**Comment by OneOfOne** [comment]
I meant run it from the same directory as your project, not from /tmp.

**Comment by FlipB** [comment]
If I wasn't clear, I tried running it with `go run` with the project root as current working directory and the target file in tmp, that did not work.
Moving the file to the project root and then running it with `go run` did work.

`go run` does not seem to honor working directory.

**Comment by OneOfOne** [comment]
I'm honestly not sure how to fix this except by creating the temp file in the cwd and run it from there, would that be acceptable?

**Comment by FlipB** [comment]
That's the most obvious solution.

Unless there's a way to change the behavior of `go run` (cmdline args? env vars?) that make it look in CWD or in a specific path for dependencies creating the file in the repo is probably the best way forward.

If it's hidden behind an option and we ensure it creates a new temp file which is automatically deleted afterwards, then it's probably acceptable, don't you think?

**Comment by OneOfOne** [comment]
I'll try to mess with it over the weekend and see if I can figure something out.

**Comment by OneOfOne** [comment]
Can you try with the latest master and let me know if it works or not please.

**Comment by FlipB** [comment]
I can confirm v1.0.4 works with vendored packages now.

Thanks.

**Comment by OneOfOne** [comment]
Great! closing this then.
