### ISSUE TITLE
Underscore in package name causes havoc

### ISSUE THREAD

**Issue by john8329** [OneOfOne/struct2ts#12]
I think I found the problem that was partially related to my previous issue. I tried generating a model from a package that was called `apps_api`, and it failed citing that it couldn't find the name (there was no import in the generated file). Renaming the package to `appsapi` worked.

Also I noticed that a package name with dashes gets converted to underscores somewhere, but I can't remember where I saw this. Maybe it's a go thing, I have no idea.

The setup is as follows:
- Module with subfolder called `apps-api` and the package is called `apps_api` (inside the subfolder)
- `go:generate` command inside an `interfaces.go` file inside the `apps-api` folder
- Running it causes an error:

`build command-line-arguments: cannot load my-server/apps_api: cannot find module providing package my-server/apps_api`

Removing the underscore from the package name fixed it temporarily.

**Comment by OneOfOne** [comment]
That's a Go thing, I can't really do much about it, I'm using `goimports` for handling those imports, without re-implementing it myself from scratch I don't see how it can handle that.

**Comment by OneOfOne** [comment]
@j0hnwhyte I got an idea, I can add an alias command line where you can pass something like `-alias apps_api=my-server/apps_api`, how do you feel about that?

**Comment by john8329** [comment]
Hackish. If it's a `goimports` issue, shouldn't we file a bug report?

**Comment by OneOfOne** [comment]
Any chance you can make a repo with the bug?
