### ISSUE TITLE
nullable arrays

### ISSUE THREAD

**Issue by benoitkugler** [OneOfOne/struct2ts#22]
Hi and thanks for this package !

From what I understand, it's common in Go to have a "nil" slice. In Go, it's not a problem since a "nil" slice behaves the same as "0 length" slice.
But when you use JSON to communicate such a slice, it gets serialized to "null", thus causing problems in TypeScript.

Thus, shouldn't be safer to switch `CanBeNull` to `true` for `Slice` and `Array` types ? 
(it's a one liner fix, in s2ts.go, line 109)

**Comment by OneOfOne** [comment]
Thanks!
