### ISSUE TITLE
Support anonymous (embedded) structs

### ISSUE THREAD

**Issue by OneOfOne** [OneOfOne/struct2ts#6]

**Comment by zmitry** [comment]
Hi, I found that one easy to implement, just add extends 
```
if sf.Anonymous && k == reflect.Struct {
			extendsType := s.addType(sft, "", "").Name
			if out.InheritType != "" {
				out.InheritType += ","
			}
			out.InheritType = extendsType
			continue
		}
```
and handle this in renderer

**Comment by OneOfOne** [comment]
A PR is welcome, I haven't had time to work on this project recently.

**Comment by zmitry** [comment]
Unfortunately I made private fork of this project, I needed only interfaces generation so It was easier to fork it.

**Comment by john8329** [comment]
I implemented a recursive approach, but the `extends` seems cleaner, although I haven't tried it. If somebody needs it I can post the code.
