### ISSUE TITLE
Allow to change the struct name to upper-case when converting

### ISSUE THREAD

**Issue by davyzhang** [OneOfOne/struct2ts#8]
Some of the structs which I don't want to export in golang, but it's weird to have many lower case classes in typescript.

I think it will be useful when we have a switch to change that

**Comment by OneOfOne** [comment]
Can you give me an example?

**Comment by OneOfOne** [comment]
Does the [AddWithName](https://godoc.org/github.com/OneOfOne/struct2ts#StructToTS.AddWithName) func help with that problem?

**Comment by davyzhang** [comment]
For now, AddWithName should be fine, as long as I don't have many structs which need to be converted 😄 

as for example
```golang

//a struct for db storage with gorm, I will send them on wire later to clients for display
type project struct {
	util.Model 

	UID   string   `json:"uid" gorm:"type:uuid;column:uid" sql:"DEFAULT:uuid_generate_v4()"`
	URL   string   `json:"url"`   //src url of news
	Title string   `json:"title"` //no more than xx words
	Cover imageUID `json:"cover"`
}
```
I usually put all the files togother in a same directory including http handlers and database schema files so that I don't have to export many structs.

```
cmd/
--out/
-----main.go <-here is the main entry
schema.go //db defination
handler.go //http handlers
entry.go //http mux and server, only export one or more functions for main entry
....
```

As you can see, in most cases my structs are named with lower case.

**Comment by OneOfOne** [comment]
Reopening, I have a simple fix for this, I'll push it later today.
