### ISSUE TITLE
NoDate option generates invalid typescript

### ISSUE THREAD

**Issue by zmitry** [OneOfOne/struct2ts#9]
I got this in typescript fie
```
	server_time: Time;
```
which is invalid

**Comment by OneOfOne** [comment]
Looking, should be have a fix out sometime today/tomorrow.

**Comment by zmitry** [comment]
any updates ?

**Comment by OneOfOne** [comment]
Can you give me the struct you used and how you generated it, seems like I can't reproduce.

**Comment by OneOfOne** [comment]
@zhDmitry can you give me some example?

**Comment by zmitry** [comment]
in 1d

**Comment by OneOfOne** [comment]
Any updates on this?
